.github/workflows/ci.yml, api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java, api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiCreateRoomRequest.java, api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/common/support/ApiTestSupport.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/constants/DaySlot.java, core/src/main/java/com/civilwar/boardsignal/room/domain/constants/TimeSlot.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Participant.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomCategory.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/request/CreateRoomResponse.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/CreateRoomRequest.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
- closed #6 
- 방 생성 api 구현
- 방 엔티티 요구사항 맞춰서 재정의하고 erd 수정해놨습니다.
- 방 생성 로직에서 Participant(유저-방 테이블) 생성해서 저장하는 로직까지 있습니다.
- 나중에 방 폭파 구현할 때 해당 방의 Participant도 다 없애야 합니다!
- Conflict 많을 것 같은데 그건 머지전에 수정하겠습니다~
- 방 생성 로직 및 테스트 코드
- 방 엔티티 재설계 한 부분
=> feat : 방 생성 API 구현

api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java, api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java, core/src/main/java/com/civilwar/boardsignal/auth/application/AuthService.java, core/src/main/java/com/civilwar/boardsignal/auth/domain/RefreshTokenRepository.java, core/src/main/java/com/civilwar/boardsignal/auth/domain/TokenProvider.java, core/src/main/java/com/civilwar/boardsignal/auth/dto/response/UserLogoutResponse.java, core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/JwtTokenProvider.java, core/src/main/java/com/civilwar/boardsignal/auth/infrastructure/RefreshTokenRedisRepository.java, core/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthMapper.java, core/src/test/java/com/civilwar/boardsignal/auth/infrastructure/RefreshTokenRedisRepositoryTest.java
- closed #3 
- 회원이 로그아웃 요청을 보낸다면
1. Redis에서 RefreshToken값을 삭제합니다.
2. Cookie의 RefreshToken ID를 삭제합니다
- 네이밍
- 전체적인 로직 흐름
- 이번 태스크는 양이 적어서 금방 리뷰하실 것 같습니다!
- 중간중간  단위테스트는 무의미한 것 같아서
1. API 통합테스트
2. Redis 저장소 테스트
만 진행하였습니다!
=> feat : 로그아웃 API 구현

api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, api/src/test/java/com/civilwar/boardsignal/common/config/CorsConfig.java, api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/BoardGame.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Wish.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/WishRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/WishBoardGameResponse.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/WishRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/WishJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/fixture/BoardGameFixture.java
- closed #22 
- 찜 등록 api 구현
- 찜 등록 시에 이미 찜한 게임이라면 찜을 취소하는 로직으로 구현했습니다. 반대로 찜하지 않았던 게임이라면 찜 등록 로직을 수행하게 했습니다.
- 찜 등록 로직
- 테스트 코드
- 컨벤션 놓친 거 없는 지
- 찜 등록 시에 보드게임 조회, 찜 조회, 찜 insert(delete), 보드게임 업데이트(찜 수) 이렇게 쿼리가 네방 나갑니다ㅠㅠ
- 이게 최선이라 생각해서 이렇게 짰는데 좋은 의견 있을 시 남겨주세용
=> feat : 보드게임 찜하기 API 구현

api/src/main/java/com/civilwar/boardsignal/boardgame/dto/mapper/BoardGameApiMapper.java, api/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/ApiAddTipRequest.java, api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Tip.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/BoardGameMapper.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/AddTipRequest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/AddTipResposne.java, core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/fixture/BoardGameFixture.java
- closed #24 
- 공략 등록 API 구현 및 테스트
- 요청으로 온 보드게임에 대해 사용자가 이미 등록된 공략이 있다면 예외 발생
- 등록된 공략이 없다면 공략 등록
- 비즈니스 로직
- 테스트 코드 추가할 부분 & 테스트 로직
=> feat : 공략 등록 API 구현

api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java, api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java, core/src/main/java/com/civilwar/boardsignal/review/domain/constant/ReviewContent.java, core/src/main/java/com/civilwar/boardsignal/review/domain/entity/Review.java, core/src/main/java/com/civilwar/boardsignal/review/domain/entity/ReviewEvaluation.java, core/src/main/java/com/civilwar/boardsignal/review/domain/repository/ReviewRepository.java, core/src/main/java/com/civilwar/boardsignal/review/infrastructure/adaptor/ReviewRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java, core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java, core/src/main/java/com/civilwar/boardsignal/user/domain/entity/UserCategory.java, core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserProfileResponse.java, core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserReviewResponse.java, core/src/main/java/com/civilwar/boardsignal/user/facade/UserReviewFacade.java, core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java, core/src/test/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepositoryTest.java, core/src/test/java/com/civilwar/boardsignal/user/facade/UserReviewFacadeTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/review/ReviewFixture.java
- closed #4 
- closed #16 
- 본인 프로필 조회 API 구현
- 타인 프로필 조회 API 구현
- UserReviewFacade -> 리뷰 데이터를 조회하고 정리하는 로직을 해당 클래스에 따로 구분하였습니다!
- Review와 1:N으로 연결된 ReviewEvaluation을 그냥 fetch join하여 함께 불러왔습니다!
- 요구사항 변경(리뷰 함께 조회)에 따라 은찬님이 구현하신 코드 (#9)에 수정하려 하였는데, conflict가 너무 많이 일어나서, 코드 참고하여 새로 pr 열었습니다..!
- commit 메시지에 설명 적어놓았습니다!
=> feat : 유저는 프로필을 조회할 수 있다.

api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/request/BoardGameSearchCondition.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/review/domain/entity/ReviewEvaluation.java, core/src/main/java/com/civilwar/boardsignal/user/facade/UserReviewFacade.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java, core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
- closed #28 
- 보드게임 검색 기능 추가
- 기존 보드게임 필터링 전체조회에 검색 키워드를 통한 조건 파라미터 추가
- api 따로 추가하진 않음
- 사실 기존 구현에 필터링 조건 하나 더 추가한거라 테스트 코드 위주로 보시면 될 것 같습니다
=> feat : 보드게임 검색 기능 구현

api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/build.gradle, core/src/main/java/com/civilwar/boardsignal/common/config/QueryDslConfig.java, core/src/main/java/com/civilwar/boardsignal/common/config/TimeConfig.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/MeetingInfo.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomCategory.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetAllRoomResponse.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomPageResponse.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/MeetingInfoJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/common/support/DataJpaTestSupport.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java, core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/MeetingInfoFixture.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
- closed #17 
- 자신이 이전에 참여했던 모임들을 조회할 수 있다
- 모임 확정 날짜 기준 자정이 지나야 해당 모임 조회
- RoomJpaRepository : 자신이 참여한 모든 모임 데이터들을 가져온 후,
- RoomService : 모든 모임 데이터들을 요구사항 조건에 맞게 필터링 한 후, Slice로 변환 부분
해당 흐름으로 가는데 service 로직에서 데이터를 걸러내고 slice로 변환해도 괜찮을까요? 
- 2~3개의 엔티티와 엮여있기에 테스트 데이터 세팅이 살짝 그렇습니다..!
- 커밋 별로 메시지 남겼습니다
=> feat : 사용자는 참여했던 모임들을 조회할 수 있다 

core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameQueryRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/BoardGameJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameConcurrencyTest.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java
- closed #36 
- 찜 등록 시 동시성 이슈 제어
- DB 비관적락 적용
- 동시성 테스트(50명이 찜 등록 시 찜 수 50)
- 이번 Pr은 작업량이 매우 적어서.. 그냥 보시면 될 것 같습니다😃
=> feat : 찜 등록에 대한 동시성 이슈 제어

api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantJpaDto.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantResponse.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomInfoResponse.java, core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java, core/src/test/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepositoryTest.java
- closed #18 
- 방 단일 조회 API
- 방 단일 조회 시 응답 요구사항
1. 방 정보
2. 모임 확정 정보
3. 참가자 정보
4. 현재 로그인한 유저 방장 여부
- RoomService 로직
- 테스트 케이스 놓친 부분?
- RoomService 부분은 커밋 메시지로 흐름을 정리하였습니다..!!
=> feat : 방을 단일조회 할 수 있다.

api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Like.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/entity/Tip.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/LikeRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/LikeTipResponse.java, core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/LikeRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/LikeJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java, core/src/test/java/com/civilwar/boardsignal/common/support/DataJpaTestSupport.java, core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
- closed #41 
- 좋아요 등록 및 취소 로직 구현
- Like 엔티티 설계
- Tip 엔티티 likeCount필드 추가 및 likeCount 증감메소드 정의
- 로직 상 빠진게 있는 지...잘 봐주시면 감사하겠슴다.
- **코드 포맷팅이 밀려서 파일 체인지가 많으니 커밋별로 리뷰 권장 드립니다!**
- API 총 2개입니다.(등록, 취소)
=> feat : 좋아요 등록 및 취소 API 구현

api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/TipRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/TipRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/TipJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/ParticipantResponse.java, core/src/test/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepositoryTest.java
- closed #50 
- 공략 삭제 구현
- tipId 받아서 tipId와 userId를 통해 자신의 공략 삭제
- soft delete아니라 그냥 삭제하는 간단한 로직으로 짰습니다.
=> feat : 공략 삭제 API 구현

api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java, api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java, core/src/main/java/com/civilwar/boardsignal/user/application/UserService.java, core/src/main/java/com/civilwar/boardsignal/user/dto/response/UserProfileResponse.java, core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java
- closed #49 
- 본인 프로필 조회 API와 타인 프로필 조회 API를 통합한다
- 프로필 User id와 프로필 주인 여부를 추가로 응답한다.
=> edit : 프로필 조회 API 수정

api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/request/RoomSearchCondition.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetAllRoomResponse.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/RoomInfoResponse.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/user/domain/constants/Gender.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java, core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
- closed #48 
1. Room Entity 수정
2. 방 생성 시 -> 
- 이성 허용 여부 true -> 혼성 입장 가능
- 이성 허용 여부 false -> 남성 또는 여성만 입장 가능
3. 방 상세정보 조회, 필터링 조회 -> 응답 필드 변경
4. 테스트 보완
- 필드랑 로직이 일부 수정됨에 따라 통합 테스트 케이스 몇 개 추가했는데 혹시 놓친 게 있는지 봐주시면 감사하겠습니다!
=> edit : 방 필터링 조회 API

api/src/main/java/com/civilwar/boardsignal/auth/dto/response/LoginUserInfoResponse.java, api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java, api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java, api/src/main/java/com/civilwar/boardsignal/review/presentation/ReviewController.java, api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
- closed #52 
- AccessToken의 담긴 유저의 정보들을 단순 반환해주는 API 입니다.
- SecurityFilter에서 얻은 user의 정보를 컨트롤러에서 매핑해서 반환합니다
- 프론트에서 필요하다하여 구현합니다!
- 가볍게 보시면 될 것 같습니다ㅎㅎ
=> feat : 클라이언트는 현재 로그인한 유저의 정보를확인할 수 있다

api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java, api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
- closed #60 
- 방 상세정보 조회 시 방장을 구별해야 합니다
1. AccessToken 존재 시 -> 방장인지 아닌지 구별하여 응답
2. AccessToken 존재하지 않을 시 -> 무조건 방장이 아님 (기능 추가된 부분)
- SecurityConfig에서 접근을 허용하여도 @AuthenticationPrincipal이 동작하는 것을 확인하여, 일단 모든 api 열어두었습니다!
- #59 pr 시 인증 필요/불필요 api 구분하겠습니다!
- pr 폭탄 죄송함다...ㅠ
=> edit : 방 상세정보는 인증되지 않은 사용자들도 접근할 수 있다

api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java, api/src/main/java/com/civilwar/boardsignal/common/config/CorsConfig.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, api/src/test/java/com/civilwar/boardsignal/review/presentation/ReviewControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/dto/response/CancelWishResposne.java, core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java, core/src/main/java/com/civilwar/boardsignal/review/domain/constant/ReviewContent.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java, core/src/test/java/com/civilwar/boardsignal/review/application/ReviewServiceTest.java
- closed #66 
- 찜 취소 API 구현
- 기존에 찜 등록 로직에 등록, 취소 로직 들어가있던 것 분리
- 찜 등록 시 -> 이미 찜이 되어있다면 예외
- 찜 취소 시 -> 찜한 적이 없다면 예외
- 로직
- 테스트 코드
- 보드게임 관련된거 말고 나머지는 코드 포맷팅이니 안 보셔도 됩니다!
=> feat : 찜 취소 API 구현

api/src/main/java/com/civilwar/boardsignal/auth/dto/response/LoginUserInfoResponse.java, api/src/main/java/com/civilwar/boardsignal/auth/mapper/AuthApiMapper.java, api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java, api/src/test/java/com/civilwar/boardsignal/auth/presentation/AuthApiControllerTest.java
- closed #70
- 현재 사용자의 나이도 함께 조회할 수 있습니다!
- 현재 나이 계산 로직
- 응답 필드만 추가된 간단한 작업입니다!
=> edit : 현재 사용자의 정보 조회 시, 나이도 함께 반환한다.

api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java, api/src/main/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameController.java, api/src/test/java/com/civilwar/boardsignal/boardgame/presentation/BoardGameControllerTest.java, core/src/main/java/com/civilwar/boardsignal/boardgame/application/BoardGameService.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Category.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/constant/Difficulty.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/BoardGameQueryRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/domain/repository/WishRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/exception/BoardGameErrorCode.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/WishRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/BoardGameJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/boardgame/infrastructure/repository/WishJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/domain/constants/DaySlot.java, core/src/main/java/com/civilwar/boardsignal/room/domain/constants/TimeSlot.java, core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java, core/src/test/java/com/civilwar/boardsignal/boardgame/application/BoardGameServiceTest.java, core/src/test/java/com/civilwar/boardsignal/boardgame/infrastructure/adaptor/BoardGameQueryRepositoryAdaptorTest.java
- closed #71 
- 찜 목록 조회는 인증된 사용자만 타인의 찜목록, 내 찜 목록 조회 가능
- userId를 통해 user의 찜 전체 조회
- 조회된 찜의 보드게임id들을 추출하여 보드게임들을 in 쿼리로 조회
- 조회 결과 리턴
- Security Config 수정 
- 스웨거 permitAll()
- 찜 목록 조회 인증 필요 
- 비즈니스 로직
- 테스트 로직
=> feat : 보드게임 찜 목록 조회 API 구현

api/src/main/java/com/civilwar/boardsignal/auth/presentation/AuthApiController.java, api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java, api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiFixRoomRequest.java, api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/common/support/ApiTestSupport.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/constants/WeekDay.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/MeetingInfo.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/MeetingInfoRepository.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/request/FixRoomRequest.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/FixRoomResponse.java, core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/MeetingInfoRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/MeetingInfoFixture.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
- closed #72 
- MeetingInfo 엔티티에 요일 필드(enum) 추가
- 응답바디 명세 수정(MeetingInfo id도 넘겨주도록)
- 비즈니스 로직
- 테스트코드
=> feat : 모임 확정 API 구현

api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/MeetingInfoRepository.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/ParticipantRepository.java, core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/MeetingInfoRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/ParticipantRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantQueryJpaRepository.java
- closed #73 
- 모임 확정 취소 API 구현
- 방 엔티티 unfix 메소드 추가
- 모임 확정 DB에서 삭제
- API 통합테스트
- 비즈니스 로직
- 테스트
- 응답 값 없이 삭제만 해서 api 통합테스트만 진행했습니다!
=> feat : 모임 확정 취소 API 구현

api/src/main/java/com/civilwar/boardsignal/notification/presentation/NotificationController.java, core/src/main/java/com/civilwar/boardsignal/notification/application/FcmSender.java, core/src/main/java/com/civilwar/boardsignal/notification/application/NotificationService.java, core/src/main/java/com/civilwar/boardsignal/notification/dto/request/NotificationRequest.java, core/src/main/java/com/civilwar/boardsignal/notification/event/NotificationEventHandler.java, core/src/main/java/com/civilwar/boardsignal/notification/exception/NotificationErrorCode.java, core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserFcmTokenRepository.java, core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserFcmTokenRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserFcmTokenJpaRepository.java
- closed #108 
- 동일한 알림이 여러명에게 가야할 경우에 대한 로직 추가(EventHandler에 구현)
- NotificationRequest 생성
- 기기 토큰 저장 시 이미 저장되어있으면 예외 발생 로직 추가
- 로직 흐름
- 다대다 관계인데 테이블 구조는 안 바꾸고 꼼수 느낌인 것 같은 구현을 했습니다..
- 일단은 구현목표로 진행한거니 로직에 이상 있는 지만 리뷰 부탁드립니다~!
=> feat : 여러명에 대한 알림 처리 & 기기 토큰 저장 로직 수정

.github/workflows/cd.yml, api/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomApiMapper.java, api/src/main/java/com/civilwar/boardsignal/room/dto/request/ApiFixRoomRequest.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/dto/request/FixRoomRequest.java, core/src/testFixtures/java/com/civilwar/boardsignal/room/RoomFixture.java
- closed #117 
- 방 필터링 통합테스트 Disabled
- 모임 확정 요청 dto 인원 수 필드 제거
- 모임 확정 서비스로직 수정
- MeetingInfo 생성 시 인원수는 방의 인원 수를 넣어 생성
- API 스펙 수정에 따른 간단 작업입니다~
=> edit : 모임 확정 API 인원 수 필드 제거

api/src/main/java/com/civilwar/boardsignal/auth/config/SecurityConfig.java, api/src/main/java/com/civilwar/boardsignal/chat/presentation/ChatMessageController.java, api/src/main/java/com/civilwar/boardsignal/chat/presentation/StompMessageController.java, api/src/test/java/com/civilwar/boardsignal/chat/presentation/ChatMessageControllerTest.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/chat/application/ChatMessageService.java, core/src/main/java/com/civilwar/boardsignal/chat/domain/entity/ChatMessage.java, core/src/main/java/com/civilwar/boardsignal/chat/domain/repository/ChatMessageRepository.java, core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatMessageDto.java, core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatPageResponse.java, core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/adaptor/ChatMessageRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/chat/mapper/ChatMessageMapper.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Room.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/ParticipantJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepositoryTest.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
- closed #79 
1. 모임 삭제 시 채팅 내역 삭제
2. 채팅 내역 조회 로직 
- 로직 & 테스트 케이스
- 커밋 별 설명을 보시는걸 추천드립니다!
=> feat : 모임 참가자는 모임 채팅 내역을 조회할 수 있다

api/src/main/java/com/civilwar/boardsignal/chat/presentation/ChatMessageController.java, api/src/main/java/com/civilwar/boardsignal/chat/presentation/StompMessageController.java, core/src/main/java/com/civilwar/boardsignal/chat/application/ChatMessageService.java, core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatMessageDto.java, core/src/main/java/com/civilwar/boardsignal/chat/dto/response/GetChatMessageResponse.java, core/src/main/java/com/civilwar/boardsignal/chat/mapper/ChatMessageMapper.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Participant.java
- closed #135 
- Participant에 채팅 페이지 퇴장 시간이 함께 기록됩니다
- 채팅 페이지 퇴장 시간은 프론트에서 별도의 메시지 송신으로 기록됩니다
- 채팅 내역 조회 시, 각각의 채팅이 이미 확인한 채팅인지 여부를 함께 반환합니다
- 첫 번째 커밋에서 roomservice는 안보셔도 됩니다
=> edit : 채팅 내역 조회 시, 채팅 확인 여부 함께 반환

core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameUsersResponse.java
- closed #137 
- 응답 dto에 imageUrl 추가
- 5초만에 리뷰 가능합니다.
=> edit : 종료된 게임에 참여한 유저 조회 API 응답 필드 수정

api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
- closed #143 
- 확정 날짜가 요청 시점보다 이전이면 예외
- 확정 날짜가 요청 시점 7일이내가 아닐 경우 예외
- Service 테스트 추가
- 추가된 검증 로직
- 테스트 코드
=> feat : 모임 확정 시 날짜 검증 추가

api/src/main/java/com/civilwar/boardsignal/auth/handler/OAuth2LoginSuccessHandler.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/review/application/ReviewService.java, core/src/main/java/com/civilwar/boardsignal/review/domain/repository/ReviewRepository.java, core/src/main/java/com/civilwar/boardsignal/review/exception/ReviewErrorCode.java, core/src/main/java/com/civilwar/boardsignal/review/infrastructure/adaptor/ReviewRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/GetEndGameResponse.java, core/src/main/java/com/civilwar/boardsignal/user/dto/response/LoginUserInfoResponse.java, core/src/main/java/com/civilwar/boardsignal/user/mapper/UserMapper.java, core/src/test/java/com/civilwar/boardsignal/review/application/ReviewServiceTest.java, core/src/test/java/com/civilwar/boardsignal/review/infrastructure/repository/ReviewJpaRepositoryTest.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
- #142 
- 리뷰 등록 시, 해당 모임의 이미 리뷰를 했는지 검증합니다
- 종료된 모임 조회 시, 해당 모임에 리뷰를 완료했는지를 응답 필드에 추가합니다
- 로그인 시, 리다이렉트 URL을 프론트 서버 도메인으로 변경합니다
- 로그인한 사용자 정보 조회 시, 이미지도 함께 반환합니다
- 추가된 쿼리
- 놓친 요구사항
=> feat : 내가 이전에 참여한 모임 조회 시, 해당 모임에 리뷰 반영 여부를 함께 반환한다

api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/RoomBlackList.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomBlackListRepository.java, core/src/main/java/com/civilwar/boardsignal/room/exception/RoomErrorCode.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomBlackListRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomBlackListJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
- closed #147
- 블랙리스트 엔티티 설계
- 참가자 추방 시, 블랙리스트 추가
- 모임 삭제 시, 모임과 관련된 블랙리스트 정보 삭제
- 모임 참여 시, 참가자 블랙리스트 확인
=> feat : 블랙리스트 추가

api/build.gradle, api/src/main/java/com/civilwar/boardsignal/ApiApplication.java, core/src/main/java/com/civilwar/boardsignal/common/config/AsyncConfig.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/user/domain/repository/UserRepository.java, core/src/main/java/com/civilwar/boardsignal/user/infrastructure/adaptor/UserRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/user/infrastructure/repository/UserJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/user/domain/repository/UserRepositoryTest.java, scheduler/build.gradle, scheduler/src/main/java/com/civilwar/boardsignal/common/config/SchedulerConfig.java, scheduler/src/main/java/com/civilwar/boardsignal/user/scheduler/UserSignalScheduler.java, settings.gradle
- closed #148 
- 스케줄러 모듈 추가
- signal 업데이트 쿼리 구현 (더티 체킹 불가하여 직접 쿼리!)
- core모듈, scheduler모듈 Thread Pool 분리
- RoomService EndGame조회 메소드의 끝난 모임 조회 로직 메소드 추출(스케줄러에서 활용)
- 로직
- 쿼리 테스트 코드
=> feat : 프로필 조회 시 signal 업데이트 된 결과 조회

api/src/main/java/com/civilwar/boardsignal/room/presentation/RoomController.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/entity/Participant.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/KickOutFacadeResponse.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/KickOutResponse.java, core/src/main/java/com/civilwar/boardsignal/room/facade/RoomFacade.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/room/application/RoomServiceTest.java
- closed #153 
- 방 생성 시, 방장의 lastExit 초기화
- 채팅 방 목록 정렬 수정
- 참가자 추방 시, 닉네임 내려주기
=> fix : 방 생성 시, 방장의 lastExit 초기화

api/src/test/java/com/civilwar/boardsignal/notification/presentation/NotificationControllerTest.java, core/src/main/java/com/civilwar/boardsignal/notification/application/FcmSender.java, core/src/main/java/com/civilwar/boardsignal/notification/event/NotificationEventHandler.java, core/src/main/java/com/civilwar/boardsignal/notification/infrastructure/adaptor/NotificationRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/notification/infrastructure/repository/NotificationJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/facade/RoomFacade.java
- closed #155 
- 이벤트 핸들러가 호출한 쪽의 메소드 트랜잭션이 끝나야 실행되기에 퍼사드 클래스 메소드에 트랜잭션 적용(RoomFacade)
- 알림 전송 로직 안에 기기 토큰 꺼내서 반복문 도는 작업 이벤트 핸들러로 이전
- 하나의 스레드가 외부 api 호출 여러번하는게 부하가 커서 오류 나는 것 같아 비동기로 처리
- 계속 프론트와 테스트해보고 잘 되는 거 확인되면 merge할 예정입니다~
- 파일체인지로 리뷰 권장드립니다!~
=> fix : 알림 버그 수정

api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, core/src/main/java/com/civilwar/boardsignal/chat/domain/repository/ChatMessageRepository.java, core/src/main/java/com/civilwar/boardsignal/chat/dto/response/ChatCountDto.java, core/src/main/java/com/civilwar/boardsignal/chat/dto/response/LastChatMessageDto.java, core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/adaptor/ChatMessageRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/room/application/RoomService.java, core/src/main/java/com/civilwar/boardsignal/room/domain/repository/RoomRepository.java, core/src/main/java/com/civilwar/boardsignal/room/dto/mapper/RoomMapper.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/ChatRoomDto.java, core/src/main/java/com/civilwar/boardsignal/room/dto/response/ChatRoomResponse.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/adaptor/RoomRepositoryAdaptor.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java, core/src/test/java/com/civilwar/boardsignal/chat/infrastructure/repository/ChatMessageJpaRepositoryTest.java, core/src/test/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepositoryTest.java
- closed #171 
1. 채팅방 목록 조회 시 응답 필드 추가
기존
- 모임 정보
변경
- 모임 정보
- 채팅방 별 읽지 않은 메시지 갯수
- 마지막으로 받은 채팅 함께 응답
(카카오톡 채팅방 목록에서 마지막 메시지 보여주는 거 생각하시면 됩니다) 
2. 채팅방 목록 조회 시, 필요한 데이터만 갖고오도록 쿼리 수정
- 쿼리를 좀 더 핏하게 갖고오도록 하엿습니다
1. 효율적인 쿼리
채팅방 목록 조회 기능에서 다음과 같이 쿼리가 3방이 나갑니다
- 채팅방 목록 조회
- 채팅방 별 읽지 않은 메시지 갯수 조회
- 채팅방 별 마지막 채팅 조회
**이 쿼리 3개를 통합해서 줄이고 싶었는데, 방법이 없는 것 같아 여쭙고 싶습니다..!**
2. 만약 위의 사항의 개선사항이 뚜렷하지 않다면, 추가된 쿼리와 테스트 케이스를 봐주시면 감사합니다
- 커밋 별로 보시면 됩니다!
=> edit : 채팅 방 조회 기능 리팩토링

api/src/main/java/com/civilwar/boardsignal/user/presentation/UserApiController.java, api/src/test/java/com/civilwar/boardsignal/room/presentation/RoomControllerTest.java, api/src/test/java/com/civilwar/boardsignal/user/presentation/UserApiControllerTest.java, core/src/main/java/com/civilwar/boardsignal/auth/application/AuthService.java, core/src/main/java/com/civilwar/boardsignal/room/infrastructure/repository/RoomJpaRepository.java, core/src/main/java/com/civilwar/boardsignal/user/domain/constants/Gender.java, core/src/main/java/com/civilwar/boardsignal/user/domain/entity/User.java
- 이전 작업에서 성별과 연령대를 더 이상 카카오 서버에서 받지 않도록 수정했습니다
- OAuth 첫 로그인 시, 폼에서 가입 처리를 하지 않고 다시 로그인 할 경우 DB에 저장되어 있지 않은 `성별`과 `연령대`를 갖고오는 로직이 있어 에러가 발생했습니다
- '알 수 없음' 성별과 연령대를 추가하여 nullpointerexception을 해결했습니다
=> hotfix : OAuth 첫 로그인 시 버그 수정
